# Generated by Django 4.1.5 on 2023-01-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='category',
            field=models.CharField(choices=[('toys', 'TOYS'), ('home', 'HOME'), ('clothes', 'CLOTHES')], max_length=8),
        ),
    ]
