# Generated by Django 4.1.5 on 2023-01-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='category',
        ),
    ]
