# Generated by Django 4.1.5 on 2023-02-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_watchlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
