# Generated by Django 4.1.5 on 2023-02-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auction_listing_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='active',
        ),
    ]
