# Generated by Django 4.1.5 on 2023-02-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_auction_listing_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='isactive',
        ),
    ]
