# Generated by Django 4.1.5 on 2023-02-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_auction_listing_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='isactive',
            field=models.BooleanField(),
        ),
    ]
