# Generated by Django 4.1.5 on 2023-02-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_auction_listing_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='active',
            new_name='isactive',
        ),
    ]
