# Generated by Django 4.1.5 on 2023-02-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_rename_active_auction_listing_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='isactive',
        ),
    ]
