# Generated by Django 4.1.5 on 2023-02-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_remove_auction_listing_isactive'),
    ]

    operations = [
    ]

# how to delete all changes that you made today in your program?
            

