# Generated by Django 4.1.5 on 2023-02-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auction_listing_active'),
    ]

    operations = [
    ]
